-- MySQL Script generated by MySQL Workbench
-- Fri 15 Nov 2019 04:53:16 PM -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Table "user_account"
-- -----------------------------------------------------
CREATE TABLE  "user_account" (
  "id" SERIAL NOT NULL,
  "name" VARCHAR(200) NOT NULL,
  "email" VARCHAR(200) NOT NULL,
  "password" TEXT NOT NULL,
  PRIMARY KEY ("id")
  );


-- -----------------------------------------------------
-- Table "client"
-- -----------------------------------------------------
CREATE TABLE  "client" (
  "id_user" SERIAL NOT NULL,
  "name" VARCHAR(200) NOT NULL,
  "email" VARCHAR(200) NOT NULL,
  "birth_date" DATE NOT NULL,
  "phone" VARCHAR(45) NULL,
  "address" VARCHAR(45) NULL,
  "occupation" VARCHAR(45) NULL,
  "cpf" VARCHAR(45) NULL,
  PRIMARY KEY ("id_user"),
  CONSTRAINT "fk_client_user1"
    FOREIGN KEY ("id_user")
    REFERENCES "user_account" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- Table "event"
-- -----------------------------------------------------
CREATE TABLE  "event" (
  "id" SERIAL NOT NULL,
  "name" VARCHAR(45) NOT NULL,
  "init_hour" VARCHAR(45) NOT NULL,
  "final_hour" VARCHAR(45) NOT NULL,
  "price" DECIMAL(10,2) NULL,
  PRIMARY KEY ("id")
);


-- -----------------------------------------------------
-- Table "activity_event"
-- -----------------------------------------------------
CREATE TABLE  "activity_event" (
  "id" SERIAL NOT NULL,
  "id_client" INT NOT NULL,
  "id_event" INT NOT NULL,
  "status" CHAR NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_activity_event_event"
    FOREIGN KEY ("id_event")
    REFERENCES "event" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT "fk_activity_event_client1"
    FOREIGN KEY ("id_client")
    REFERENCES "client" ("id_user")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- Table "check_in"
-- -----------------------------------------------------
CREATE TABLE  "check_in" (
  "id" SERIAL NOT NULL,
  "id_activity_event" INT NOT NULL,
  "init_hour" VARCHAR(45) NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_checkin_activity_event1"
    FOREIGN KEY ("id_activity_event")
    REFERENCES "activity_event" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- Table "certification"
-- -----------------------------------------------------
CREATE TABLE  "certification" (
  "id" SERIAL NOT NULL,
  "id_activity_event" INT NOT NULL,
  "title" VARCHAR(500) NOT NULL,
  "description" TEXT NOT NULL,
  "authentication" TEXT NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "fk_certification_activity_event1"
    FOREIGN KEY ("id_activity_event")
    REFERENCES "activity_event" ("id")
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);


-- -----------------------------------------------------
-- Table "email"
-- -----------------------------------------------------
CREATE TABLE  "email" (
  "id" SERIAL NOT NULL,
  "receiver_mail" VARCHAR(500) NOT NULL,
  "sent_mail" VARCHAR(500) NOT NULL,
  "reason" TEXT NOT NULL,
  PRIMARY KEY ("id")
);


DROP SEQUENCE IF EXISTS "certification_id_sequence";
CREATE SEQUENCE  "certification_id_sequence";
ALTER TABLE "certification" ALTER COLUMN "id" SET DEFAULT NEXTVAL('"certification_id_sequence"');
DROP SEQUENCE IF EXISTS "email_id_sequence";
CREATE SEQUENCE  "email_id_sequence";
ALTER TABLE "email" ALTER COLUMN "id" SET DEFAULT NEXTVAL('"email_id_sequence"');
